# Install pre-commit hooks via:
# pre-commit install

# yapf = yet another python formatter
repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    name: yapf
    args: ["-i"]
